### ISSUE TITLE
A better structure for `ImageDraw.jl`

### ISSUE THREAD

**Issue by annimesh2809** [JuliaImages/ImageDraw.jl#11]
Currently, there are some structural and naming issues in `ImageDraw.jl`:
1. `line` is a method for drawing a line while `Line` is an abstract type denoting a line.
2. `line` used with `LineTwoPoints` draws only a line segment while `line` used with `LineNormal` draws an infinite line on the image, which breaks consistency.
3. Function names like `line`, `ellipse`, `path` etc. do not clearly suggest whether they are methods to draw an object on an image or methods to create a new drawable object.

I suggest the following changes in the API:
1. Any object that can be drawn on an image like `Line`, `Ellipse`, `Polygon` etc. should derive from `Drawable` abstract type.
2. A single method `draw` to draw `Drawable` object(s) on an image(or multiple images). `draw` would use multiple dispatch to draw the specific objects onto the image. This would produce a much neater API.
3. The addition of `RegularPolygon <: Drawable` to draw a regular polygon on an image. This could be used to define other shapes like `Square`, `EquilateralTriangle` etc.
4. `Line` would be used to draw infinite lines and `LineSegment` would be used to draw a line segment of a specific length.
![imagedraw jl](https://cloud.githubusercontent.com/assets/15063205/24719150/5234c79e-1a56-11e7-9828-0c390e28ddef.png)

Kindly suggest if these changes are relevant. If so, then I can start working on this.

**Comment by timholy** [comment]
I like it! Including the diagram.

My only tiny suggestion would be to call the method `draw!`, since it modifies the image. Of course you could provide a copying `draw` function built on top of `draw!`. But the non-copying version will be much more useful if you plan to do a lot of drawing on a single image.

**Comment by mronian** [comment]
Nice idea @annimesh2809!

**Comment by Evizero** [comment]
I am also a fan. I am looking forward to this

**Comment by annimesh2809** [comment]
Thanks for encouraging my idea. I have started with the implementation.
As `ImageDraw.jl` is not a registered package, should we add deprecation warnings for usage of old syntax?

**Comment by timholy** [comment]
If it's not hard, by all means add them, but since it's not registered I don't think it's required.

**Comment by bjarthur** [comment]
should this be closed now that #13 is merged?

**Comment by timholy** [comment]
Yeah. We should register this package now, I think. I guess it needs docs, though.

**Comment by annimesh2809** [comment]
@timholy I would love to add the docs to this package! I read about [`Documenter.jl`](https://juliadocs.github.io/Documenter.jl/stable/man/guide.html) and will be using it to create the docs. As this is my first time writing documentation for a julia package, any do's and don'ts or any useful references?

**Comment by SimonDanisch** [comment]
Btw, i'm slowly finishing up my pure julia implementation of GLVisualize, which can draw to `Matrix{<:Colorant}` directly, but also compiles to opengl, or maybe even svg/pdf... 
Right now particles, text, meshes and images work in a prototype kind of state.
Polygons should be relatively straight forward to add and I'm working on bringing lines in as well. Let me know if there is interest in collaboration. I'm also interested in offering a more direct API for drawing all kind of different shape types!
A lot of things like polygon triangulation and spline interpolation should be offered in a backend agnostic purely geometrical way anyways ;) Maybe as part of GeoemtryTypes, or so...

**Comment by timholy** [comment]
@annimesh2809, I guess the major question is whether it should be standalone or be added to the docs at https://github.com/JuliaImages/juliaimages.github.io. I've tended to move towards centralization of the documentation in the hopes that it will be easier for users to find that way. As far as specific tips, an important component will be image display; perhaps the "indexing.md" page there may serve as an example?

@SimonDanisch, I'm very excited about the more general backend to GLVisualize---I'm really excited about standardizing on (GL)Visualize. Until that is functional, however, this package has several advantages, including the fact that (1) it works today, (2) it's not undergoing a lot of churn, and (3) it has minimal dependencies. If anything, I wonder if you might want to basically use this package (or steal code from it) for implementing some of your line-drawing or polygon-drawing?

**Comment by SimonDanisch** [comment]
>(3) it has minimal dependencies

Well, that will hopefully be similar :)

> If anything, I wonder if you might want to basically use this package (or steal code from it) for implementing some of your line-drawing or polygon-drawing?

That doesn't make much sense for me, since I'm writing the code in a way, that it works seamlessly on the GPU :( From a short look at the algorithms here, it doesn't look like it could be used that way.

But if you're happy with the API, I might be interested in stealing that :P
