### ISSUE TITLE
Circle / Ellipse Drawing

### ISSUE THREAD

**Issue by mronian** [JuliaImages/ImageDraw.jl#2]
PR #3 will handle general circle/ellipse drawing. Implementations of circle/ellipse perimeter drawing like the bresenham algorithm still need to be implemented as they are faster.

**Comment by SimonDanisch** [comment]
May I ask why the wheel is reinvented with this package? ;)

**Comment by mronian** [comment]
This is just like 1% of the functionality of `GLVisualize` :) , just some basic drawing functions found in most image processing packages with a simple API which a person can use directly as part of `JuliaImages` without having to add the entire `GLVisualize`.

**Comment by SimonDanisch** [comment]
What about Cairo? Is it not stable enough?
Are what are the concerns?

**Comment by mronian** [comment]
I did not know about ```Cairo.jl```. In this (https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_arc.jl) is it possible to use an Image/Array with the ```arc``` function without creating a Cairo context?

**Comment by mronian** [comment]
For example, I need to draw all keypoints and the matches between them. Will something like this be possible?

```
map(k -> circle!(img1, k, radius = 10), keypoints1)
map(k -> circle!(img2, k, radius = 10), keypoints2)
offset = CartesianIndex(size(img2))
grid = hcat(img1, img2) 

map((k1, k2) -> line!(grid, k1, k2+offset), keypoints1, keypoints2)
```

**Comment by SimonDanisch** [comment]
well probably not exactly like this, but I'm sure there is a way to achieve this!

**Comment by mronian** [comment]
I haven't really used ```Cairo``` but going through the documentation, it seems a bit complicated. If someone does need a better graphics library, he can move on to Cairo (which is the case with ```opencv``` etc as well, they don't have a great drawing module but just the basic functions which are required most of the time). But if just basic stuff is required, this module will be good enough and there is no need to learn another package. 

What do you think?

**Comment by mronian** [comment]
Another example would be when a person is tracking some object in a video or image and wants it to be marked with the bounding box. Most of the cases in Computer Vision would require simple drawing functions like the ones in this module.

For a more graphics intensive case, like augmented reality where you have a canvas and need to draw complicated figures (2D/3D), something like ```Cairo``` or ```GLVisualize``` will anyways be the first choice and an image processing library would be used for just for the object detection for example.

**Comment by mronian** [comment]
ccing @timholy for advice :)

**Comment by mronian** [comment]
Merging #1, #3(needs tests) for now (they contain what I needed for keypoints). Rest of the functions are subject to the outcome of this discussion and will be done later.

**Comment by timholy** [comment]
I'm positive on the idea of this package. Binary dependencies are sometimes a barrier, and Cairo's performance has occasionally been less than impressive. I once tested a draw-lines-to-a-buffer algorithm long ago (I think it's archived on the mailing list), and a pure julia implementation was several times faster. I don't know whether that's still true, though---bugs/performance problems do tend to get fixed over time...

I haven't looked at GLVisualize's code, but if it's using the GPU to do the drawing, I'd say this is not redundant. Our headless server with no DISPLAY will thank you :smile:.

**Comment by SimonDanisch** [comment]
Okay fair enough :) Yeah, this is of course not redundant with GLVisualize ;)

**Comment by mronian** [comment]
![res](https://cloud.githubusercontent.com/assets/6151667/17465699/d9a2fb3a-5d1c-11e6-9ef2-61a859610919.jpg)

First results of using `ImageDraw` with BRIEF descriptor and FAST keypoints!
