### ISSUE TITLE
Add a cross

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/ImageDraw.jl#24]
I often need to mark something in the image without obscuring it so much. A cross does exactly that. 

I'll therefor try to PR something like this:
```julia
struct Cross <: Drawable
    c::Point
    arm::Int
end

function draw!(img::AbstractArray{T, 2}, cross::Cross, color::T) where T<:Colorant
    for x in -cross.arm:cross.arm
        img[cross.c.y, cross.c.x + x] = color
    end
    for y in -cross.arm:cross.arm
        img[cross.c.y + y, cross.c.x] = color
    end
    img
end
```

**Comment by yakir12** [comment]
Pinging the person who last committed here, hope that's ok, if not, I apologize.  
@johnnychen94

**Comment by johnnychen94** [comment]
I saw the PR when you opened it, but unfortunately, I'm not the right person to review it; I'm still quite new many of JuliaImages packages, including this `ImageDraw.jl`.

cc: @mronian

**Comment by yakir12** [comment]
Ah, I see, thanks. Well, it's a really simple PR, very basic. In fact I'm expecting some requests to add some features (e.g. cross line thickness etc)...
