### ISSUE TITLE
request for a maintainership

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageDraw.jl#33]
Looks like this package isn't maintained very actively; Several good feature PRs are pending, and docs are missing. 

If currently nobody's interested in maintaining this, I'd like to take the place. CC: @Codyk12

**Comment by johnnychen94** [comment]
bump

**Comment by juliohm** [comment]
Thank you @johnnychen94 for taking care of the JuliaImages ecosystem ❤️
