### ISSUE TITLE
doclinks broken

### ISSUE THREAD

**Issue by tbenst** [JuliaImages/ImageDraw.jl#43]
There are some docs for this package: https://github.com/JuliaImages/ImageDraw.jl/blob/master/docs/src/index.md

But the docs link in README is broken

**Comment by dehann** [comment]
I had a quick look and the dev docs link is working, but stable docs are not being built or deployed and hence no page is found.

**Comment by dehann** [comment]
Default keyword is there for dev and stable docs:
https://github.com/JuliaDocs/Documenter.jl/blob/ee0d535e519704c4a6148cb0b3c225ad07517ead/src/Documenter.jl#L454

and local setup is not changing the default...
https://github.com/JuliaImages/ImageDraw.jl/blob/ffd307393e48a3e95dccb9104e162cc586d2153f/docs/make.jl#L5

hmmm, not sure why stable is not building

**Comment by johnnychen94** [comment]
This is because the docs were set up after v0.2.3, should be available with the v0.2.4 release.
