### ISSUE TITLE
Friendly request for patch release v0.2.4

### ISSUE THREAD

**Issue by dehann** [JuliaImages/ImageDraw.jl#48]
Hi, I'm running into a compatibility problem downstream where `Distances@v0.10.0` is definitely required but the latest available tag on ImageDraw.jl only has compat support for Distances up to v0.9.  I see the CompatHelper PR for v0.10 was merged here in October #44 but has not made it into a stable tag just yet. Hence a request for a new patch release if at all possible please.

**Comment by johnnychen94** [comment]
Thanks for the reminder, I've bumped the version.
