### ISSUE TITLE
Discussion on circle fill,circle stroke option 

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/ImageDraw.jl#50]
I needed those for example : Detection and measurement,indentification of circular objects in a image
Even though Luxor.jl provides functions for that,would we need it here?Just a simple circular,elliptical drawable is unintuitive when we explain more advanced ideas there
Idea: https://github.com/ashwani-rathee/Demos/blob/main/%F0%9F%8E%88%202.pdf
relevant issues:
https://github.com/JuliaImages/ImageEdgeDetection.jl/issues/21
![](https://i.imgur.com/QDHfjAN.png)
![](https://i.imgur.com/E2WXBN1.png)

What I kind of need
![](https://in.mathworks.com/help/examples/images/win64/DetectCirclesExample_04.png)
@johnnychen94 What do you think?

**Comment by johnnychen94** [comment]
I guess we need two extra keywords `thickness` and `fill::Bool` to get this done. As you can see, writing demos do help us find out what the missing functionalities are.

Never get a chance to use `Luxor`, though. The demos there looks quite nice but I don't know if it gives an out-of-box experience to draw on an image; it might not support the `AbstractArray{<:Colorant}` image type.

**Comment by ashwani-rathee** [comment]
Okay,I'll start working on that.Yeah,writing demos kindof requires some taste in design,presentation,experimenting with various values/types of same thing(learned that from front-end person in our team,he took his time but whatever came out was usually better than what rest 3 of us made by quite a margin)...
