### ISSUE TITLE
Release, for ImageCore compat

### ISSUE THREAD

**Issue by IanButterworth** [JuliaImages/ImageDraw.jl#61]
ImageCore 0.9 is supported on master, but a release is needed

cc. @johnnychen94

**Comment by johnnychen94** [comment]
Given that it's @ashwani-rathee adding many features here. I was waiting for him to call for a release 😄 

Those many features are incremental changes, so I think it's safe to tag a new patch release and just made it.

**Comment by IanButterworth** [comment]
Thanks!
